### ISSUE TITLE
Config 

### ISSUE THREAD

**Issue by djomen** [skybrud/Skybrud.Umbraco.GridData#1]
Hi,

Is there a reason you haven't converted the Config on GridEditor to a GridConfig object rather than JObject?  Is it because there could be further properties added that we don't know about at that point.

Also, I have been converting the editor templates for the items so can do a pull request if you want to include them for examples - when i've finished converting them?

Cheers
Damian

**Comment by abjerner** [comment]
Thanks for your feedback ;)

Most of the model was implemented before the final release of Umbraco 7.2, and `config` was part of the JSON model then. Then when 7.2 was released, I couldn't find any documentation for the grid, so `JObject` was just the easy choice. I how now implemented the `GridEditorConfig` class which holds a `Style` and a `Markup` property.

I'm not sure that I understand you about the editor templates? Can you elaborate a bit on this? I have also committed some other changes, so perhaps this has solved your issue.

**Comment by djomen** [comment]
Hi - i've been away so only just read this....

With the editor templates i mean the renderer templates for the grid output to match the new strongly typed models.

Damian

**Comment by abjerner** [comment]
Sorry for not getting back to you on this one. 

I don't believe the package should provide any templates by default - this could for instance cause problems when later upgrading the package if the templates have been changed.

Instead, the documentation should provide useful examples - eg. like my sample repository here: https://github.com/abjerner/UmbracoGridDataDemo/tree/master/dev/web/Views/Partials/TypedGrid

I hope that makes sense ;)
