### ISSUE TITLE
LeBlender and GridData

### ISSUE THREAD

**Issue by wiedikerli** [skybrud/Skybrud.Umbraco.GridData#10]
Hi! I'm using the leblender for all my controls. But i don't know how to pass the model from the framework to the actual control partial.     

What is also confusing is that the value of the control is null. Is that cause of the blender?

This is my framework:

```
@inherits UmbracoViewPage<GridDataModel>
@if (Model != null && Model.Sections.Any())
{
    <div class="grid">
        @foreach (var section in Model.Sections)
        {
            foreach (var row in section.Rows)
            {
                foreach (var area in row.Areas)
                {
                    foreach (var control in area.Controls)
                    {
                        <div class="grid-row">
                            @Html.Partial("Grid/Editors/" + control.Editor.Alias.ToFirstUpper(), (object)control.JObject) // <= struggling here
                        </div>
                    }
                }
            }
        }
    </div>
}
```

Here is one Editor: 

```
@inherits UmbracoViewPage<LeBlenderModel>
@if (Model != null && Model.Items.Any()) {}
```

When i use the base then it works also with the blender.

```
@Html.Partial("grid/editors/base", (object)control.JObject)
```

**Comment by abjerner** [comment]
Hi Tobias,

I haven't worked with LeBlender so I don't think I'm able to help you much with that.

As for the value of the control being `null`, the package relies on a number of converters.

By default, I have implemented two converters - one for handling the [default controls in Umbraco](https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/master/src/Skybrud.Umbraco.GridData/Converters/Umbraco/UmbracoGridConverter.cs), and another for handling [controls in the Fanoe starter kit](https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/master/src/Skybrud.Umbraco.GridData/Converters/Fanoe/FanoeGridConverter.cs). Both converters implements the `IGridConverter` interface, which describes three different methods: `ConvertControlValue`, `ConvertEditorConfig` and `GetControlWrapper`.

The idea with the converters is that when the package is parsing a control in the grid model (the JSON from the grid), the package will run through the converters and use the `ConvertControlValue` method for converting the control value into a strongly typed object and use the `ConvertEditorConfig` method for converting the editor config into a strongly typed model as well. 

The converters are kept in an ordered list, so if the first converter doesn't know how to parse a given control value, the package will continue to the next converter. If no converters know how to parse the control value, the `Value` property will simply be `null` (as you're experiencing).

If we assume that we have a custom editor with the alias `video`, you need to implement your own converter that handles controls using this editor. When implementing the `IGridConverter` interface, you could then have a `ConvertControlValue` method that looks like:

``` C#
public bool ConvertControlValue(GridControl control, JToken token, out IGridControlValue value) {

    // Start by setting the value to null
    value = null;

    // Check for the editor alias matching our custom editor        
    if (control.Editor.Alias == "video") {

        // Parse the JToken into a strongly typed model (that implements the IGridControlValue interface)
        value = GridControlVideoValue.Parse(control, token);

    }

    // Return whether our converter could handle the control
    return value != null;

}
```

Similarly if the editor has a configuration, we can also handle that through the `ConvertEditorConfig` method:

``` C#
public bool ConvertEditorConfig(GridEditor editor, JToken token, out IGridEditorConfig config) {

    // Start by setting the config to null
    config = null;

    // Check for the editor alias matching our custom editor    
    if (editor.Alias == "video") {

        // Parse the JToken into a strongly typed model (that implements the IGridEditorConfig interface)
        config = GridEditorVideoConfig.Parse(editor, token as JObject);

    }

    return config != null;

}
```

I know this can be a bit complex, so I hope it makes sense ;)

**Comment by AndersBrohus** [comment]
@abjerner 

Have you tried working with LeBlender since this issue was opened? :)
I'm trying to find some information about making an custom search function, since Google is closing the paid service of Site Search :)

**Comment by abjerner** [comment]
@AndersBrohus No, not really. We have only used LeBlender on a few projects, but I haven't used it myself.

Anyways, what should your search function do? If you have a grid property (eg. called `content`), Umbraco should already have taken care of the JSON for you, so the corresponding `content` field in the external Examine index only will contain the textual values of the grid model. For a simple search, this should be enough.

**Comment by AndersBrohus** [comment]
Arha okay.. :)

I would like to make an simple search, that takes all text on the page and search through this :)
Maybe i should also look at the Examine and see if the text is there :)

@abjerner

**Comment by abjerner** [comment]
@AndersBrohus Then an Examine search should suffice ;)

**Comment by abjerner** [comment]
@ninjaonsafari Since more people have requested this, I've now release a new package which adds support for LeBlender:

https://github.com/skybrud/Skybrud.Umbraco.GridData.LeBlender

Let me know if you have nay feedback ;)
