### ISSUE TITLE
ModelsBuilder generates wrong type

### ISSUE THREAD

**Issue by kipusoep** [skybrud/Skybrud.Umbraco.GridData#11]
When I install this package in an umbraco v7.4.1 instance, ModelsBuilder generates the following field:

``` csharp
///<summary>
/// Content
///</summary>
[ImplementPropertyType("content")]
public object Content
{
    get { return this.GetPropertyValue("content"); }
}
```

This should be `GridDataModel` right?

**Comment by abjerner** [comment]
I really don't know about ModelsBuilder, but yes, something like below should do the trick:

``` C#
///<summary>
/// Content
///</summary>
[ImplementPropertyType("content")]
public GridDataModel Content
{
    get { return this.GetPropertyValue<GridDataModel>("content"); }
}
```

**Comment by kipusoep** [comment]
Yeah I know, but it should be generated correctly. Other plug-ins with PropertyValueConverters work fine, only this one doesn't. So I guess it's a bug in this project.
