### ISSUE TITLE
Match on editor view

### ISSUE THREAD

**Issue by ronaldbarendse** [skybrud/Skybrud.Umbraco.GridData#17]
Please change the matching for `IGridControlValue`, `IGridEditorConfig` and `GridControlWrapper` in `UmbracoGridConverter` to use the editor `View`, instead of `Alias`.

For example within the `ConvertControlValue` method:

```c#
switch (control.Editor.View) {
    case "textstring":
        value = GridControlTextValue.Parse(control, token);
        break;
}
```

This way, we don't have to create custom `IGridConverter` classes for other grid editors based on textstring (using different config/markup).

**Comment by abjerner** [comment]
Thanks for creating the issue 👍 

In retrospect, the converters should probably have been made this way to begin with. I'l will look into updating that ;)

However it could be seen as a breaking change, so I need to look into that aspect as well. Most users will probably not notice a change like that, so it might just be that I bump the version number to `2.1.x`, and then write something about in the release notes (if people are actually reading that).

**Comment by ronaldbarendse** [comment]
No problem, thanks for creating the package! 🥇 

Since the grid editor view is tightly coupled with the instances of `IGridControlValue` and `IGridEditorConfig`, the only 'downside' would be matching additional editors that otherwise would be matched using a custom converter.

The API doesn't change, but bumping to 2.1.0 and having a corresponding release note would indeed be the 'right thing' to do...

**Comment by abjerner** [comment]
I've now updated the `UmbracoGridConverter` class to look at the view instead of the alias, and pushed this as part of [**v2.0.5**](https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v2.0.5) ;)
