### ISSUE TITLE
Move FanoeGridConverter to own package

### ISSUE THREAD

**Issue by ronaldbarendse** [skybrud/Skybrud.Umbraco.GridData#18]
Most of the custom grid editors within the `FanoeGridConverter` could be removed if issue #17 is resolved, so only the following custom editors would require this converter:

- `media_text_right`: /App_Plugins/Grid/Editors/Views/media_with_description.html
- `quote_D`: /App_Plugins/Grid/Editors/Views/quote_with_description.html

To keep this package clean and decoupling the core functionality from the Fanoe starter kit, I would recommend moving this class to its own package (just like LeBlender).

**Comment by abjerner** [comment]
Hey @ronaldbarendse,

Can't even remember why I didn't reply to this issue when you created the issue 🤔 

While a good idea, I don't think is something that's worth fixing now as Umbraco 8 is now the current major version.
