### ISSUE TITLE
GridControlMediaValue has no AltText

### ISSUE THREAD

**Issue by ronaldbarendse** [skybrud/Skybrud.Umbraco.GridData#19]
The media grid editor also contains an `altText` property that is not exposed in `GridControlMediaValue`:

- https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI/Views/Partials/Grid/Editors/Media.cshtml
- https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.controller.js

**Comment by abjerner** [comment]
Closing here as the pull request is now merged. Thanks again ;)
