### ISSUE TITLE
Allow parsing single GridControl from JObject

### ISSUE THREAD

**Issue by ronaldbarendse** [skybrud/Skybrud.Umbraco.GridData#21]
For backend preview rendering (using a custom grid control or LeBlender for example), only the JSON for the control itself is provided as model. I've not found an easy solution to parse a single control to the data models, because it requires a section, that requires a row, that requires an area, etc.

For now, I've used the following workaround to render a single grid control (`\Views\Partials\Grid\Editors\Base.cshtml`):

```C#
@model JObject
@using Newtonsoft.Json.Linq;
@using Skybrud.Umbraco.GridData
@{
    Layout = null;

    // Workaround to get a parsed grid control
    var grid = GridDataModel.GetEmptyModel();
    var control = GridControl.Parse(GridArea.Parse(GridRow.Parse(GridSection.Parse(grid, new JObject()), new JObject()), new JObject()), Model);

    // Use editor alias as partial view
    var view = Model.GetValue("editor").Value<string>("alias");
}
@control.GetHtml(Html, view)
```

**Comment by abjerner** [comment]
I'm not sure I understand the problem. Is this specifically for LeBlender previews in the backoffice?

**Comment by ronaldbarendse** [comment]
It is indeed more specific to LeBlender then the custom grid controls, because LeBlender shows a rendered preview and opens the editor in a dialog (with generic property editors). Other grid controls have special editor views that are shown in the backoffice and allow direct editing of content (using Angular bindings and therefore don't interact with GridData).

Maybe the best option is to add an extension method to the [Skybrud.Umbraco.GridData.LeBlender](https://github.com/skybrud/Skybrud.Umbraco.GridData.LeBlender) package with the provided workaround (eg. `Html.GetTypedGridControlHtml`) and provide instructions to use this to render the previews.

BTW I think the model JObject is actually a [LeBlenderModel](https://github.com/Lecoati/LeBlender/blob/master/Src/Lecoati.LeBlender.Extension/Models/LeBlenderModel.cs), but I have to verify that first...

**Comment by abjerner** [comment]
Support for LeBlender is currently not a priority for this package, but I'll try to have a look at it when I can find some time ;)

I think LeBlender uses JSON.net to cast a `JObject` into a `LeBlenderModel`. If we have the original `JObject`, we can maybe traverse up the JSON structure to parse the entire grid model.
