### ISSUE TITLE
GetAllControls() returns nothing

### ISSUE THREAD

**Issue by Mantus667** [skybrud/Skybrud.Umbraco.GridData#23]
I'm currently testing the package with Umbraco 7.7.x and trying to deserialize the json of a grid for adding content to examine properly.

For this, I'm using your gist as a base and it seems that the deserialization kind of works but GetAllControls() returns none.

Any hints on this?

**Comment by abjerner** [comment]
@Mantus667 Thanks for creating an issue. I haven't heard about or experienced any issues with Umbraco 7.7 (I can't remember whether I've used that particular method in 7.7), but I will investigate further ;)

Anyways, do you by any change have some more context about your issue? Do you call `GetAllControls` with or without any parameters? You write that this is for indexing in Examine - does the same method work fine in regular MVC views? If the deserialization encounters any errors, you should be able to see some information about the error/exception in the Umbraco log. Is there anything there that could help?

**Comment by Mantus667** [comment]
@abjerner will have a look at the log and see if there is any interesting stuff in there.
Also, will try to have a look if any problems occur in a view.
Will try to post a dump of the deserialized object. Maybe there are some errors in it that I'm not aware of.
I'm calling the method without any parameters.
Grid configuration should be pretty basic. Nothing special there I think.

**Comment by Mantus667** [comment]
Ok after investigating the problem was in front of the computer and not the code.
The page I debugged with had no content in the grid causing the grid to not be valid.
After testing with data everything is working!
