### ISSUE TITLE
Umbraco V8

### ISSUE THREAD

**Issue by mirkomaty** [skybrud/Skybrud.Umbraco.GridData#27]
Is it planned to update the package for Umbraco v.8?

We might help doing that, if there aren't good reasons not to do it.

**Comment by abjerner** [comment]
Hi @mirkomaty 

I wasn't sure how much it took to convert it to Umbraco 8, so gave it a quick try. Turns out it didn't take that much, so I've pushed a new beta release here:

https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v3.0.0-beta001

The works the same as in Umbraco 7 😉

**Comment by mirkomaty** [comment]
Wow, that was pretty fast. Thanks a lot.

And guess what? I did the same thing yesterday. Now I compared my work with yours and it's pretty much the same. ;-)

**Comment by AndersBrohus-MySupport** [comment]
@mirkomaty or @abjerner :)

Any luck you guys have some code/documentation on how to use the GetSearchableText() function in an "custom index creator" in V8? :)

**Comment by abjerner** [comment]
@AndersBrohus-MySupport from what I can tell the raw grid value is never added to the index, and as such we can't parse it.

The indexing of the grid seems to be controlled by this class:

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web/PropertyEditors/GridPropertyIndexValueFactory.cs

But I think the raw value should be added to the index, so it might be worth raising this as an issue for Umbraco 😉

<hr />

However a **hack** could be to look up the `IPublishedContent` of the node - eg. as done in this component:

```csharp
public class RegisterExamineEventsComponent : IComponent {

    private readonly IExamineManager _examineManager;
    private readonly IUmbracoContextAccessor _accessor;
    private readonly IUmbracoContextFactory _factory;

    public RegisterExamineEventsComponent(IExamineManager examineManager, IUmbracoContextAccessor accessor, IUmbracoContextFactory factory) {
        _examineManager = examineManager;
        _accessor = accessor;
        _factory = factory;
    }

    public void Initialize() {
        if (_examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out IIndex index)) {
            ((BaseIndexProvider)index).TransformingIndexValues += OnTransformingIndexValues;
        }
    }

    public void Terminate() { }

    private void OnTransformingIndexValues(object sender, IndexingItemEventArgs e) {

        // Get an instance of UmbracoContext
        UmbracoContext context = _accessor.UmbracoContext ?? _factory.EnsureUmbracoContext().UmbracoContext;
        
        // Get the published content
        IPublishedContent content = context.Content.GetById(int.Parse(e.ValueSet.Id));
        if (content == null) return;

        // Get the grid data model
        GridDataModel grid = content.Value<GridDataModel>("bodyText");

        // Add the searchable text to the value set
        e.ValueSet.Set("bodyTextSearchableText", grid.GetSearchableText());

    }

}
```

**Comment by mirkomaty** [comment]
@abjerner: Thanks a lot for figuring out this solution. I searched for a replacement for OnExamineGatheringNodeData, and your code does the trick!
