### ISSUE TITLE
Editor property of GridControls not populated after Cloud content restore

### ISSUE THREAD

**Issue by skttl** [skybrud/Skybrud.Umbraco.GridData#29]
When restoring content from Umbraco Cloud, the Editor property on a GridControl is not populated correct. 

![billede](https://user-images.githubusercontent.com/3726467/64422569-aac8a180-d0a4-11e9-85c2-0c2e6c7dc6ff.png)

Once you save/publish the node, the property gets populated correct
![billede](https://user-images.githubusercontent.com/3726467/64422640-d8154f80-d0a4-11e9-9532-91ad06958669.png)

It seems like Deploy is missing some information in the json blob, which gets re-added by Umbraco on save.

I found this line: https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/2421f198bcc8435640f30c00edd872470751b321/src/Skybrud.Umbraco.GridData/GridControl.cs#L299
It takes the editor config from the config if Umbraco is bigger than 7.3 (but not 8.x). If I change it to `if (UmbracoVersion.Current.Major > 7 || (UmbracoVersion.Current.Major == 7 && UmbracoVersion.Current.Minor >= 3)) Howdy.ReplaceEditorObjectFromConfig(control);` the Editor property gets populated correct.

I haven't tested what happens in "Vanilla" Umbraco.

**Comment by hfloyd** [comment]
Thank you!!!! I was having this issue - "render" was missing from the "editor" information, which was causing errors on the front-end. the beta0003 release fixed the issue for me!
