### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by naepalm** [skybrud/Skybrud.Umbraco.GridData#3]
I've noticed there are a lot of fantastic updates to this plugin and I was wondering if you were going to update the NuGet package for it :)

**Comment by abjerner** [comment]
Hi Janae,

Yes, hopefully I'll be able to make a new release in one of the following days ;)

I have just pushed some code that should make up the codebase for the next release. I haven't really tested it that much yet, so I need do that first. But other than that, it should be ready for release.

**Comment by abjerner** [comment]
I didn't have as much time as expected, so took a bit longer than just "the following days". I have now pushed a new release to NuGet:

https://www.nuget.org/packages/Skybrud.Umbraco.GridData/1.1.0

The documentation is still a little behind, but I will try to correct that tomorrow ;)

**Comment by naepalm** [comment]
That's fantastic! Thank you so much :) Excited to see the update!

Janae Cram, Developer
Mindfly Studio
114 W Magnolia St, Suite 300
Bellingham, WA 98225
360.647.7470
