### ISSUE TITLE
Clash of value converters with GridPropertyValueConverter

### ISSUE THREAD

**Issue by iOvergaard** [skybrud/Skybrud.Umbraco.GridData#34]
Version of package: 2.0.6

Version of Umbraco: 7.15.3

Hello,

Let me start by saying perhaps I'm using this package in the wrong way, but the only thing I need from this package is the ability to index all grid controls in Examine and this package provides a very nice way to build models for the grid controls and eventually call `GetSearchableText()` on the whole grid 👍 

However, I am using another package, which comes with its own value converter for the `Umbraco.Grid` property type, and Skybrud.Umbraco.GridData also registers a value converter for this property, and it seems there is no way to disable the latter.

The Examine indexer converts the raw JSON of the grid using `GridDataModel.Deserialize`, so I don't really need your value converter for the grid, but I can't seem to find a way to disable your converter.

My solution thus far has been to pull in the source of this package and simply delete the file `GridPropertyValueConverter.cs` and everything just works after that, but this approach feels messy.

Is there a way to disable the value converter so I can keep using the Nuget package?

**Comment by abjerner** [comment]
Hi @Jacob87,

This package doesn't feature anything that let's you disable the property value converter. But Umbraco let's you remove property value converters during startup, so maybe something like below does the trick:

```csharp
public void OnApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
{
    PropertyValueConvertersResolver.Current.RemoveType<Skybrud.Umbraco.GridData.GridPropertyValueConverter>();
}
```

I don't have an active test solution for the Umbraco 7 package at the moment, so I haven't tested the code above, but we've used this method successfully for other property value converters in the past.

Out of curiosity, what other package are you using for the grid?

**Comment by iOvergaard** [comment]
Hi @abjerner 

That is a very interesting approach. You kind of have to guess what the value converter is called, though, so maybe that snippet could be added to the README?

This particular project stems from the beta programme of what was then known as Umbraco Headless. It comes with a value converter for the grid that makes it output URLs instead of UDIs and stuff like that.
