### ISSUE TITLE
.","ExceptionMessage":"A member with the name 'name' already exists on 'Skybrud.Umbraco.GridData.GridDataModel'. 

### ISSUE THREAD

**Issue by untiedshoes** [skybrud/Skybrud.Umbraco.GridData#35]
Hi,

Using Umbraco 8.5.5, with a custom 'CamelCasePropertyNamesContractResolver', to get around the issue with the circular reference in Nested Content, I'm getting the following error:

`{"Message":"An error has occurred.","ExceptionMessage":"A member with the name 'name' already exists on 'Skybrud.Umbraco.GridData.GridDataModel'. Use the JsonPropertyAttribute to specify another name.","ExceptionType":"Newtonsoft.Json.JsonSerializationException","StackTrace":"   at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property) in /_/Src/Newtonsoft.Json/Serialization/JsonPropertyCollection.cs:line 118\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:line 1364\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:line 340\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:line 1249\r\n   at Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver.ResolveContract(Type type) in /_/Src/Newtonsoft.Json/Serialization/CamelCasePropertyNamesContractResolver.cs:line 71\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 516\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 469\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 703\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 469\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 703\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 469\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 703\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 95\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 1151\r\n   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 664\r\n   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 629\r\n   at Umbraco8cms.web.Controllers.ApiController.GetAllArticles() in C:\\Users\\untie\\source\\repos\\2020\\Umbraco8CMS\\Umbraco8cms.web\\Umbraco8cms.web\\Controllers\\ApiController.cs:line 140\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}`

Any ideas?
Regards,
Craig

**Comment by abjerner** [comment]
@untiedshoes sorry for forgetting this issue 😊

I think this is because there is both a `Name` property as well as a `name` property. The latter is there to avoid a breaking change so you can still use a `dynamic` approach.

Normally this should be a problem when serializing instances of `GridDataModel`, as the `GridJsonConverter` converter is used by default. But with your resolver, it seems that the JSON converter from the package is ignored, thus resulting in the exception you've posted.

I think the fix would be to add `[JsonIgnore]` to both the `name` and `section` properties:

https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/master/src/Skybrud.Umbraco.GridData/GridDataModel.cs#L61

https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/master/src/Skybrud.Umbraco.GridData/GridDataModel.cs#L67

If you can share a bit of your code, I can try to see if adding the attributes actually fixes it 😉

**Comment by abjerner** [comment]
Hi @untiedshoes,

I haven't heard back from you, so I haven't been able to test this fully - but in theory the issue should be fixed in the upcoming release 😉
