### ISSUE TITLE
Suggestion: Add Doc Type Grid Editor (DTGE) support

### ISSUE THREAD

**Issue by jcdcdev** [skybrud/Skybrud.Umbraco.GridData#36]
Hey, firstly I'd like to thank you for creating this package; I don't hate working with the grid anymore! 🥇 

I also love using [Doc Type Grid Editor](https://github.com/skttl/umbraco-doc-type-grid-editor) to make some really powerful Grid Controls and would like to create an extension package, much like you have for [LeBlender](https://github.com/skybrud/Skybrud.Umbraco.GridData.LeBlender).

I've created a new class library in my fork [here](https://github.com/jcdcdev/Skybrud.Umbraco.GridData/tree/feature/dtge-integration/src/Jcdcdev.Umbraco.GridData.DocTypeGridEditor). It also enables developers to extract searchable text from their strongly typed DTGE grid controls 😀

Do you want to have any input on this? I'd be happy for you to take it under the Skybrud namespace if you're willing to help turn it into a package.

I'm also able to maintain my own package but I'd like to hear your thoughts on this first 😄

I'll aim to put together a demo repo over the weekend that shows how one could render and index a few DTGE controls.

**Comment by abjerner** [comment]
Hi @jcdcdev and thanks for the feedback 😄

Sorry for the lack of reply. You created this issue while I was on vacation, and I haven't been able to catch up until now 🌴 🏖️ 

I did start out on [**Skybrud.Umbraco.GridData.Dtge**](https://github.com/skybrud/Skybrud.Umbraco.GridData.Dtge) for Umbraco 7 a while back, but I haven't really worked on it for more than year. We've been using DTGE ourselves for Umbraco 7, so I'm not sure why I didn't finish and release this as a package.

I don't have a preference towards either approach. I'd be happy to update the **Skybrud.Umbraco.GridData.Dtge** codebase to Umbraco 8, and then you're welcome to add your changes via a PR. Or if you release your own package, I'm fine with that as well 😉 

For the technical part, I think you have found a nice solution with the `ISearchableTextConverter` interface and related logic. I've been planning on adding a similar concept to the main **Skybrud.Umbraco.GridData** package along with better use of dependency injection. Ideally Skybrud.Umbraco.GridData.Dtge/your package could utilize that once it's implemented. But for now, it could just as well be "standalone" as in your fork.

Let me know what you think 😉

**Comment by jcdcdev** [comment]
Hi @abjerner, I hope you had a good vacation!

I wish I saw that repository before I started - I think it would be best for the code to fall under the **Skybrud** namespace as I want people to be able to find and use it. I'd be happy to add some documentation to the this repo's readme to boost its exposure. 

Let me know once the codebase is updated to Umbraco 8 and I'll make a PR 😄 

I'm glad you like my approach with `ISearchableTextConverter`. I'd be happy to make a PR into this codebase, changing the methods to take an instance of a `GridControl` so that it can support _any_ `GridControl` 😀. If you'd rather do it yourself then I can include what I've already done in the **Skybrud.Umbraco.GridData.Dtge** PR as I think it still adds value.

**Comment by abjerner** [comment]
Hi @jcdcdev,

I found a bit of time to work on this, although there is still some work left.

I've created a [dependency-injection-and-more](https://github.com/skybrud/Skybrud.Umbraco.GridData/tree/v3/dev/dependency-injection-and-more) branch in the `Skybrud.Umbraco.GridData`. It improves the use dependency injection, and changes how you add a new grid converter (so it's now more similar to how you add other things from a composer).

The branch also introduces the [IGridElementConverter.cs](https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/v3/dev/dependency-injection-and-more/src/Skybrud.Umbraco.GridData/Converters/IGridElementConverter.cs) interface, which describes a single method for getting the textual representation of an `IPublishedElement`:

```csharp
public interface IGridElementConverter : IGridConverter {

    bool GetSearchableText(GridContext context, IPublishedElement element, out string text);

}
```

The Skybrud.Umbraco.GridData.Dtge now also has a [v2/dev](https://github.com/skybrud/Skybrud.Umbraco.GridData.Dtge/tree/v2/dev) branch that utilizes these changes. Calling the `GetSearchableText` method on a DTGE based control will now run through all grid converters implementing `IGridElementConverter` and ask to get a searchable text for the `IPublishedElement` in question.

The grid converter in the DTGE grid package doesn't know how to convert your elements into text, but you can add your own grid converter for that - eg. as I've done here:

```csharp
using System.Text;
using Skybrud.Umbraco.GridData;
using Skybrud.Umbraco.GridData.Converters;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Models.PublishedContent;
using UmbracoEightSeven.Models.Website.Pages;

namespace UmbracoEightSeven.Composers {

    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    internal class TestComposer : IUserComposer {
        
        public void Compose(Composition composition) {

            composition.GridConverters().Append<TextGridConverter>();

        }

    }

    public class TextGridConverter : GridConverterBase, IGridElementConverter {
        
        public bool GetSearchableText(GridContext context, IPublishedElement element, out string text) {
            
            StringBuilder sb = new StringBuilder();
            
            text = null;

            switch (element) {

                case Feature feature:
                    sb.AppendLine(feature.FeatureName);
                    sb.AppendLine(feature.FeatureDetails);
                    text = sb.ToString();
                    return true;

                default:
                    return false;

            }

        }

    }

}
```

It's still work in progress, but it seems to work really well so far.

As most of the logic for making this possible is is located in the main grid package, I don't think there is need for you to create a PR for the DTGE grid package. But we can see more about than going forward.

**Comment by abjerner** [comment]
Hi @jcdcdev 

Not sure whether this would still be useful with Umbraco 9 coming out soon, but I've pushed a release of [**Skybrud.Umbraco.GridData.Dtge**](https://github.com/skybrud/Skybrud.Umbraco.GridData.Dtge) 😉 

It works much like the concepts I describe earlier - eg. with the `IGridElementConverter` interface and it's `GetSearchableText` method.
