### ISSUE TITLE
IsValid returns false wrongly

### ISSUE THREAD

**Issue by skartknet** [skybrud/Skybrud.Umbraco.GridData#37]
For some reason, IsValid() returns false but I can't find anything wrong with the data:

{"name":"1 column layout","sections":[{"grid":12,"rows":[{"label":"1 Column","name":"1 Column","areas":[{"grid":12,"allowAll":false,"allowed":["imageComponent","rteComponent","fccCtaComponent","horizontalCardsComponent","verticalCardsComponent","bannerTwoColumnsImageText"],"hasConfig":false,"controls":[{"value":{"dtgeContentTypeAlias":"bannerTwoColumnsImageText","value":{"name":"Banner Two Columns - Image and Text","title":"Need our help?","description":"<p><span>You may be entitled to a range of benefits or insurance through your super.</span><br /><br /><span>Use our free online claim check to start your</span><br /><span>assessment.</span></p>","image":"29631","link":[{"id":"1198","name":"Home","udi":"umb://document/263b8492f63c41dfa16872fb3f828a54","url":"/","icon":"icon-circus","published":true}],"states":["4336"]},"id":"e01ebf5c-2aee-44a4-5061-33f7cef7f79c"},"editor":{"alias":"bannerTwoColumnsImageText"},"active":false},{"value":{"dtgeContentTypeAlias":"bannerTwoColumnsImageText","value":{"name":"Banner Two Columns - Image and Text","title":"Need our help?","description":"<p><span>You may be entitled to a range of compensation benefits.</span><br /><span>Use our free online claim check to start your free</span><br /><span>assessment.</span></p>","image":"13974","link":[{"id":"29512","name":"Check Now","target":"_blank","udi":"umb://document/331f79a226f54828a5d51e1becea6612","url":"/free-claim-check/","icon":"icon-ordered-list color-blue-grey","published":true}],"states":["4337"]},"id":"f7c00628-9a26-1951-4cf1-39ef360481ca"},"editor":{"alias":"bannerTwoColumnsImageText"},"active":false}]}],"hasConfig":false,"id":"56f3f195-13e9-828f-9fe1-987eedaa1f0b"}]}]}

**Comment by skartknet** [comment]
Is the package compatible with DTGE? Maybe that's the problem?

**Comment by abjerner** [comment]
Hi @skartknet,

In this class, each control is represented by the `GridControl` class. That class has a `Value` property, which is of the type `IGridControlValue` (which then actually will be a class implementing the interface - eg. `GridControlTextValue`).

Validation in this package works by asking the different controls whether they are valid. A `GridControl` instance is considered valid if it has a value and that value is also considered valid:

https://github.com/skybrud/Skybrud.Umbraco.GridData/blob/v3/latest/src/Skybrud.Umbraco.GridData/GridControl.cs#L76

For instance you may be able to insert a RTE control, but if the actual RTE value is empty, the control and control value will be considered invalid (as there is no text to show).

If the grid package doesn't know how to handle a given control (or editor), the `Value` property will also be `null`. This would be the case with DTGE, as this package doesn't know how to handle DTGE. This also means that the control will be considered invalid.

I can't see from your description which version of Umbraco that you're using. I did start out on an addon for DTGE, which you can find for Umbraco 7 here:

https://github.com/skybrud/Skybrud.Umbraco.GridData.Dtge/tree/v1/latest

And for Umbraco 8 here:

https://github.com/skybrud/Skybrud.Umbraco.GridData.Dtge/tree/v2/latest

Neither are available on NuGet, and I can't remember for sure how much progress I actually made. I'll suggest pulling down the source code and testing it locally to see whether it helps with your issue 😉

**Comment by skartknet** [comment]
Hi @abjerner ,
Thanks for that great explanation. It really makes things clear. I'm using V7. I can give a try to that code you share there. Cheers!
