### ISSUE TITLE
Build Error about System.Web.Mvc, Version=5.2.3.0 (v1.5.0 & Umbraco v7.2.8)

### ISSUE THREAD

**Issue by hfloyd** [skybrud/Skybrud.Umbraco.GridData#6]
Hi Anders,
I just used NuGet to install the latest version (v1.5.0) into both my Umbraco root project and my custom code project. I am using Umbraco v7.2.8.

When I build, I get this error:

```
Error   7   Assembly 'Skybrud.Umbraco.GridData, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' c:\MySite\sourcecode\src\packages\Skybrud.Umbraco.GridData.1.5.0\lib\net45\Skybrud.Umbraco.GridData.dll MySite.Web
```

Should I use v1.1.0 of GridData instead?

Thanks,

Heather

**Comment by abjerner** [comment]
Hi Heather,

Yes, you can install `v1.1.0` for Umbraco 7.2.x instead. Just notice that there is a bug if you're using the embed control (see 69014590cc6c57059998cb3854c1fcce50d110b9).

I haven't yet found the exact culprit that is causing the error you're describing, but we have experienced something similar in one of our own projects. This only seems to be an issue when installing or upgrading to `v1.5.0` in an existing Umbraco 7.2.x installation.

Prior to releasing `v1.5.0`, I had tested it with different versions of Umbraco 7.2.x, and hadn't found any issues - but these were all fresh installations. So using `v1.5.0` in a fresh Umbraco 7.2.x installation should work just fine ;)

**Comment by hfloyd** [comment]
Thanks for the info, Anders.
By "fresh installation", I assume you mean a site which hasn't been upgraded from an older version of Umbraco?

This site I had the build error on is a new site, and hasn't been upgraded. However, I did install the umbraco binaries via NuGet, - if that makes any difference....?

At any rate, I think v1.1 will be fine for my use until the site DOES get upgraded to Umbraco 7.3 :-)

**Comment by abjerner** [comment]
Hi again,

Yes, I meant Umbraco installations that hadn't been upgraded. At least my tests showed that it worked fine, but I will investigate further ;)

For our own project, we solved it by upgrading MVC to version 5. This seems to work fine, but may affect Razor intellisense in VS2012 (which I still use on some computers) - VS2013 should be fine.

**Comment by hfloyd** [comment]
Okay, If I have any issues and need to upgrade, I'll keep those tips in mind. Thanks!
